services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: calssiq/eportal:node-env
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

