services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: calssiq/eportal:env-js-node18
    init: false
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

